export const GET_POSTS = 'GET_POSTS'
export const GET_POSTS_LOADING = 'GET_POSTS_LOADING'
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR'

export const REGISTRY_LOADING = 'REGISTRY_LOADING'
export const REGISTRY_SUCCESS = 'REGISTRY_SUCCESS'
export const REGISTRY_ERROR = 'REGISTRY_ERROR'