export const GET_POSTS = 'GET_POSTS'
export const GET_POSTS_LOADING = 'GET_POSTS_LOADING'
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR'

export const REGISTRY_LOADING = 'REGISTRY_LOADING'
export const REGISTRY_SUCCESS = 'REGISTRY_SUCCESS'
export const REGISTRY_ERROR = 'REGISTRY_ERROR'

export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const LOGOUT_LOADING = 'LOGOUT_LOADING'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'